# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      # Install poetry
      - pip install poetry
    post_install:
      # Install dependencies
      - poetry install --with docs

# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Build documentation with MkDocs (alternative)
# Uncomment to use MkDocs instead of Sphinx
# mkdocs:
#   configuration: mkdocs.yml
#   fail_on_warning: false

# Python requirements
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: requirements.txt

# Formats
formats:
  - pdf
  - epub
  - htmlzip

# Search
search:
  ranking:
    api/v2/*: -1
    api/v1/*: -2
